services:
  - type: pserv
    runtime: docker
    name: neo4j-dozerdb
    plan: starter
    envVars:
      - key: NEO4J_AUTH
        sync: false
      - key: ENABLE_OPENGDS
        value: "true"
      - key: OPENGDS_VERSION
        value: 2.12.0
      - key: NEO4J_server_memory_pagecache_size
        value: 512M
      - key: NEO4J_server_memory_heap_initial__size
        value: 512M
      - key: NEO4J_server_memory_heap_max__size
        value: 512M
      - key: NEO4J_server_directories_data
        value: /data
      - key: NEO4J_server_directories_logs
        value: /data/logs
      - key: NEO4J_server_directories_import
        value: /data/import
      - key: NEO4J_server_directories_plugins
        value: /data/plugins
    disk:
      name: neo4j-data
      mountPath: /data
      sizeGB: 10
